#!/bin/bash

# var
input=''
execute=''
slash=''
precise=''
win2cyg=''
autocmd=''

function print_usage ()
{
    echo "Convert cygwin-string to windows-string and excute it"
    echo "Options:"
    echo "  -a <files>  convert command.exe to command with 'cyg2win -e -r -i command.exe \$*'"
    echo "  -i <input>  convert input string"
    echo "  -r          convert by win2cyg"
    echo "  -e          execute it, if -r present, input use cyg2win, ouput use win2cyg"
    echo "  -p          use cygpath to precise convert each exist paths"
    echo "  -s          use slash(\\) instead of backslash(/)"
    echo "  -h          show this help and exit"
    echo "by liqiang (2018/06/06)"
    exit 1
}

# Parsing params
while getopts a:i:reshp opt; do
    case $opt in
        a) autocmd="$OPTARG" ;;
        i) input="$OPTARG" ;;
        r) win2cyg=1 ;;
        e) execute=1 ;;
        p) precise=1 ;;
        s) slash=1 ;;
        ?) print_usage ;;
    esac
done

# auto generate cyg2win command
if [[ -n "$autocmd" ]]; then
    dir="$(realpath "$autocmd")"
    for exe in $(ls "$dir"); do
        if [[ "$exe" == *.exe ]]; then
            cygexe=$(basename -s .exe "$exe")
            if [[ -d "$dir" ]]; then
                exe="$dir/$exe"
            fi
            echo "generating $cygexe ..."
            cat >$cygexe << EOF
#!/bin/bash
cyg2win -e -r -i "'$exe' \$*"
EOF
            chmod +x "$cygexe"
        fi
    done
    exit 0
fi

# check input
if [[ -z "$input" ]]; then
    # read stdin
    IFS='' read -d '' -r input
    # check
    if [[ -z "$input" ]]; then
        exit 0
    fi
fi

# root direcotry (D:/cygwin64)
root_dir=$(cygpath -m /)

# convert
if [[ -n "$win2cyg" && -z "$execute" ]]; then
    if [[ -n "$precise" ]]; then
        result=''
        for i in $input; do
            result="${result}$(cygpath -u $i) "
        done
    else
        result=$(sed "s#\\\\\\+#\\/#g; \
                      s#$root_dir/#/#Ig; \
                      s#\\([A-Za-z]\\):/#/cygdrive/\\l\\1/#g" <<<"$input")
    fi
else
    # cygwin dir keyword
    user_dir=$(cygpath ~)       # /home/username
    # convert
    if [[ -n "$precise" ]]; then
        result=''
        for i in $input; do
            i=${i/\~/$user_dir}
            if [[ -e "$i" ]]; then
                result="${result}$(cygpath -m $i) "
            else
                result="${result}${i} "
            fi
        done
    else
        result=$(sed "s#${user_dir}/#${root_dir}${user_dir}/#g; \
                      s#/cygdrive/\\([a-z]\\)/#\\1:/#g; \
                      s#~/#${root_dir}${user_dir}/#g; \
                      s#\\(^\\|\\s\\|\"\\)/\\([A-Za-z0-9._-]\\+\\)/#\\1${root_dir}/\\2/#g" <<<"$input")
    fi
    # slash
    if [[ -n "$slash" ]]; then
        result=${result//\//\\\\}
    fi
fi

# excute
if [[ -n "$execute" ]]; then
#    echo "$result"
    if [[ -n "$win2cyg" ]]; then
        eval "$result" 2>&1 | cyg2win -r
    else
        eval "$result"
    fi
else
    echo "$result"
fi
