#!/bin/bash
#
# clippaste - "Paste" data from clipboard to stdout
#
# Usage:
#
#   clippaste   - writes clipboard's contents to stdout
#
#   clippaste | <command>    - pastes contents and pipes it to another process
#
#   clippaste > <file>      - paste contents to a file
#

# Try X
if command -v xclip >/dev/null 2>&1; then
    xclip -out -selection clipboard 2>/dev/null
    result=$?

elif command -v xsel >/dev/null 2>&1; then
    xsel --clipboard --output 2>/dev/null
    result=$?
fi

# X may be not valid
[[ "$result" == "0" ]] && exit 0

# No X
if [[ $OSTYPE == darwin* ]]; then
    pbpaste

elif [[ $OSTYPE == cygwin* ]]; then
    cat /dev/clipboard

elif [[ -n "$ANDROID_DATA" ]]; then
    termux-clipboard-get

elif [[ -n "$WSL_DISTRO_NAME" ]]; then
    clipdata="$(powershell.exe -NoProfile -NonInteractive –ExecutionPolicy Bypass -Command Get-Clipboard | tr -d '\r')"
    echo -n "$clipdata"

else
    echo "clippaste: Platform $OSTYPE not supported or xclip/xsel not installed" >&2
    exit 1
fi

