#!/bin/bash
#
# clipcopy - Copy data to clipboard
#
# Usage:
#
#  <command> | clipcopy    - copies stdin to clipboard
#  clipcopy <files>         - copies a file's contents to clipboard
#  clipcopy -f <files>      - copies a file (not contents) to clipboard
#

if [[ "$1" == '-f' ]]; then
    copyfile=1
    shift
fi

file=$1

# Copy files
if [[ -n "$copyfile" ]]; then
    files=''
    if [[ $OSTYPE == cygwin* ]]; then
        for i in $@; do
            path="$(realpath "$i")"
            [[ -z "$path" ]] && exit 1
            files="$files $(cygpath -w "$path")"
        done
        # https://github.com/rostok/file2clip.git
        # https://github.com/roryyorke/picellif.git
        picellif.exe $files
        exit

    elif [[ -n "$WSL_DISTRO_NAME" ]]; then
        for i in $@; do
            path="$(realpath "$i")"
            [[ -z "$path" ]] && exit 1
            files="$files $(wslpath -w "$path")"
        done
        picellif.exe $files
        exit

    else
        print "clipcopy: Platform $OSTYPE not supported -f option" >&2
        exit 1
    fi
fi

# Try X
if command -v xclip >/dev/null 2>&1; then
    if [[ -z "$file" ]]; then
        xclip -in -selection clipboard >/dev/null 2>&1
        result=$?
    else
        xclip -in -selection clipboard "$file" >/dev/null 2>&1
        result=$?
    fi

elif command -v xsel >/dev/null 2>&1; then
    if [[ -z "$file" ]]; then
        xsel --clipboard --input >/dev/null 2>&1
        result=$?
    else
        xsel --clipboard --input < "$file" >/dev/null 2>&1
        result=$?
    fi
fi

# X may be not valid
[[ "$result" == "0" ]] && exit 0

# No X
if [[ $OSTYPE == darwin* ]]; then
    if [[ -z "$file" ]]; then
        pbcopy
    else
        pbcopy < "$file"
    fi

elif [[ $OSTYPE == cygwin* ]]; then
    if [[ -z "$file" ]]; then
        cat > /dev/clipboard
    else
        cat "$@" > /dev/clipboard
    fi

elif [[ $OSTYPE == linux-android ]]; then
    if [[ -z "$file" ]]; then
        termux-clipboard-set
    else
        termux-clipboard-set < "$file"
    fi

elif [[ -n "$WSL_DISTRO_NAME" ]]; then
    if [[ -z "$file" ]]; then
        clip.exe
    else
        clip.exe < "$file"
    fi

else
    echo "clipcopy: Platform $OSTYPE not supported or xclip/xsel not installed" >&2
    exit 1

fi

