#!/bin/bash
#
# clipcopy - Copy data to clipboard
#
# Usage:
#
#  <command> | clipcopy    - copies stdin to clipboard
#  clipcopy <files>         - copies a file's contents to clipboard
#  clipcopy -f <files>      - copies a file (not contents) to clipboard
#

if [[ "$1" == '-f' ]]; then
    copyfile=1
    shift
fi

file=$1

if [[ -n "$copyfile" ]]; then
    result=''
    if [[ $OSTYPE == cygwin* ]]; then
        for i in $@; do
            path="$(realpath "$i")"
            [[ -z "$path" ]] && exit 1
            result="$result $(cygpath -w "$path")"
        done
        # https://github.com/rostok/file2clip.git
        file2clip.exe $result < /dev/null
        exit

    elif [[ -n "$WSL_DISTRO_NAME" ]]; then
        for i in $@; do
            path="$(realpath "$i")"
            [[ -z "$path" ]] && exit 1
            result="$result $(wslpath -w "$path")"
        done
        file2clip.exe $result
        exit

    else
        print "clipcopy: Platform $OSTYPE not supported -f option" >&2
        exit 1
    fi
fi

if [[ $OSTYPE == darwin* ]]; then
    if [[ -z "$file" ]]; then
        pbcopy
    else
        pbcopy < "$file"
    fi

elif [[ $OSTYPE == cygwin* ]]; then
    if [[ -z "$file" ]]; then
        cat > /dev/clipboard
    else
        cat "$@" > /dev/clipboard
    fi

elif [[ $OSTYPE == linux-android ]]; then
    if [[ -z "$file" ]]; then
        termux-clipboard-set
    else
        termux-clipboard-set < "$file"
    fi

elif [[ -n "$WSL_DISTRO_NAME" ]]; then
    if [[ -z "$file" ]]; then
        clip.exe
    else
        clip.exe < "$file"
    fi

else
    if command -v xclip > /dev/null 2>&1; then
        if [[ -z "$file" ]]; then
            xclip -in -selection clipboard
        else
            xclip -in -selection clipboard "$file"
        fi

    elif command -v xsel > /dev/null 2>&1; then
        if [[ -z "$file" ]]; then
            xsel --clipboard --input
        else
            xsel --clipboard --input < "$file"
        fi

    else
        print "clipcopy: Platform $OSTYPE not supported or xclip/xsel not installed" >&2
        exit 1
    fi
fi

