#!/bin/bash

cmdpath="$(command -v "$1" 2>/dev/null)"
if [[ ! -f "$cmdpath" ]]; then
    echo "No such command: $1"
    exit 1
fi

if [[ -n "$WSL_DISTRO_NAME" ]]; then
    # no tmux
    touch /tmp/.notmux.tmp
    # init file
    echo "$@" > /tmp/.init.tmp
    echo "exit" >> /tmp/.init.tmp
    # Startup wsl.exe to create new instance, and use "cmd.exe /c start /b"
    setsid >/dev/null 2>&1 cmd.exe '/c' start '/b' wsl.exe -d "$WSL_DISTRO_NAME" --exec "$SHELL" -i &
else
    # >/tmp/setsid.${1##*/}.log
    setsid >/dev/null 2>&1 "$@" &
fi
