#!/bin/bash

cmdpath="$(command -v "$1" 2>/dev/null)"
if [[ ! -f "$cmdpath" ]]; then
    echo "No such file: $1"
    exit 1
fi

if [[ -n "$WSL_DISTRO_NAME" ]]; then
    # windows exe should use "cmd.exe /c start" to create daemon
    if grep -q -i "\.exe$" <<< "$1"; then
        setsid >/tmp/setsid.${1##*/}.log 2>&1 cmd.exe /c start "$@" &
        exit
    fi
fi

setsid >/tmp/setsid.${1##*/}.log 2>&1 "$@" &

