#!/bin/bash

cmdpath="$(command -v "$1" 2>/dev/null)"
if [[ ! -f "$cmdpath" ]]; then
    echo "No such file: $1"
    exit 1
fi

if [[ -n "$WSL_DISTRO_NAME" ]]; then
    # Startup wsl.exe to create new instance, and use "cmd.exe /c start /b"
    initfile=/tmp/wsl_daemon_init.$$.tmp
    cat >$initfile << EOF
export PATH='$PATH'
$@
rm $initfile
EOF
    setsid >/dev/null 2>&1 cmd.exe '/c' start '/b' wsl.exe bash -c "source $initfile" &
else
    # >/tmp/setsid.${1##*/}.log
    setsid >/dev/null 2>&1 "$@" &
fi
