#!/bin/bash
######################################################################
# @file dl
# @brief 
# @date Thu, Dec 20, 2018  5:34:20 PM
# @author liqiang
######################################################################

dir="$HOME/downloads"
session="aria2.session"
configsys="$HOME/.config/aria2/aria2.conf"
configtracker="$HOME/.aria2tracker.conf"
uilocal="$HOME/github/AriaNg/index.html"
uiurl="http://ariang.mayswind.net/latest"
trackerurl="https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best_ip.txt"
config_cfg=""
inputfile_cfg=""
max_con_per_server_cfg=""
dlthing=""

# Parse argument
for i in "$@"
do
    case $i in
        -i)
            ignore_unfinished=1
            shift
            ;;
        -u)
            ui=1
            shift
            ;;
        -t)
            tracker_update=1
            shift
            ;;
        -d=*)
            dir="${i#*=}"
            shift
            ;;
        -h|--help)
            echo "Faster downloader (aria2)"
            echo "Usage: dl [option] [url/file]"
            echo "Options:"
            echo "  -i          Ignore unfinished tasks"
            echo "  -u          Show ui"
            echo "  -t          BT tracker update"
            echo "  -d=<dir>    Set download directory"
            echo "  -NUM        Set number of max connection per server. default 16 in aria2.conf"
            echo "  -h          Show this help and exit"
            echo "by liqiang (2018/12/20)"
            exit 0
            ;;
        *)
            if [[ "$(echo $i | awk '/^-[0-9]+$/')" == "$i" ]]; then
                max_con_per_server_cfg="--max-connection-per-server=${i#*-}"
                shift
            else
                dlthing="$*"
                break
            fi
            ;;
    esac
done

# ui
if [[ ! -z "$ui" ]]; then
    if [[ -f "$uilocal" ]]; then
        open "$uilocal"
    else
        open "$uiurl"
    fi
    exit
fi

# tracker
if [[ ! -z "$tracker_update" ]]; then
    list=$(wget -O- "$trackerurl" | awk NF | sed ":a;N;s/\\n/,/g;ta")
    cp -f "$configsys" "$configtracker"
    echo "bt-tracker=$list" >>"$configtracker"
    echo "$configtracker: bt-tracker=$list"
    exit
fi

# dir
if [[ ! -d $dir ]]; then
    mkdir -p "$dir"
fi

# config
if [[ -f $configtracker ]]; then
    config_cfg="--conf-path='$configtracker'"
fi

# resume ?
save_session="$dir/$session"
if [[ -s $save_session && ! -z "$dlthing" ]]; then
    echo "$save_session:"
    echo "===================="
    cat "$save_session"
    echo "===================="
    echo ""
    read -r -p "There are unfinished tasks, ignore those? [yN] " answer
    if [[ "$answer" != "y" ]]; then
        echo -e "\e[32mPlease use UI to add this task: $dlthing\e[0m"
        echo -e "\e[32mNow resume unfinished tasks!\e[0m"
        dlthing=""
    fi
fi

# input file
if [[ -z "$dlthing" ]]; then
    if [[ -s $save_session && -z "$ignore_unfinished" ]]; then
        inputfile_cfg="--input-file='$save_session'"
    fi
elif [[ -f "$dlthing" && "$dlthing" != *.torrent ]]; then
    inputfile_cfg="--input-file='$dlthing'"
    dlthing=""
fi

# create command
cmd="aria2c --dir='$dir' --save-session='$save_session' $config_cfg $max_con_per_server_cfg"
if [[ -z "$dlthing" ]]; then
    cmd="$cmd $inputfile_cfg"
else
    cmd="$cmd '$dlthing'"
fi

# execute
echo "####################"
echo "$cmd" | sed -e 's/ \+$//g' -e 's/ \+/\n/g'
echo "####################"
eval "$cmd"

