#!/bin/bash
######################################################################
# @file dl
# @brief 
# @date Thu, Dec 20, 2018  5:34:20 PM
# @author liqiang
######################################################################

dir="$HOME/downloads"
session="aria2.session"
configsys="$HOME/.config/aria2/aria2.conf"
configtracker="$HOME/.aria2tracker.conf"
uilocal="$HOME/github/AriaNg/index.html"
uiurl="http://ariang.mayswind.net/latest"
trackerurl="https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best_ip.txt"
config_cfg=""
inputfile_cfg=""
max_con_per_server_cfg=""
misc_cfg=""
dlthing=""

function run_tracker_update ()
{
    list=$(wget -O- "$trackerurl" | awk NF | sed ":a;N;s/\\n/,/g;ta")
    cp -f "$configsys" "$configtracker"
    echo "bt-tracker=$list" >>"$configtracker"
    echo "$configtracker: bt-tracker=$list"
}

function usage ()
{
    echo "Faster downloader (aria2)"
    echo "Usage: dl [option] [url/file]"
    echo "Options:"
    echo "  -i          Ignore unfinished tasks"
    echo "  -ui         Show ui"
    echo "  -t          Update BT tracker"
    echo "  -p          Priority download header"
    echo "  -m          Just download torrent file"
    echo "  -ls         List torrent included files"
    echo "  -ls=1,3-9   Select torrent included files to download (List by -ls)"
    echo "  -d=<dir>    Set download directory"
    echo "  -NUM        Set number of max connection per server. default 16 in aria2.conf"
    echo "  -h          Show this help and exit"
    echo "  --help      Show aria2c help"
    echo "  --xxx       As aria2c option"
    echo "by liqiang (2018/12/20)"
    exit 0
}

# Parse argument
for i in "$@"
do
    case $i in
        -i) ignore_unfinished=1; shift ;;
        -ui) ui=1; shift ;;
        -t) tracker_update=1; shift ;;
        -p) misc_cfg="$misc_cfg --bt-prioritize-piece=head"; shift ;;
        -m) misc_cfg="$misc_cfg --enable-rpc=false --bt-metadata-only=true --bt-save-metadata=true --bt-load-saved-metadata=false"; shift ;;
        -ls) misc_cfg="$misc_cfg --show-files"; shift ;;
        -ls=*) misc_cfg="$misc_cfg --select-file=${i#*=}"; shift ;;
        -d=*) dir="${i#*=}"; shift ;;
        --*) misc_cfg="$misc_cfg $i"; shift ;;
        -h) usage ;;

        *)
            if [[ "$(awk '/^-[0-9]+$/' <<< $i)" == "$i" ]]; then
                max_con_per_server_cfg="--max-connection-per-server=${i#*-}"
                shift
            else
                dlthing="$*"
                break
            fi
            ;;
    esac
done

# ui
if [[ ! -z "$ui" ]]; then
    if [[ -f "$uilocal" ]]; then
        open "$uilocal"
    else
        open "$uiurl"
    fi
    exit
fi

# tracker
if [[ ! -z "$tracker_update" ]]; then
    run_tracker_update
    exit
fi

# dir
if [[ ! -d $dir ]]; then
    mkdir -p "$dir"
fi

# config
if [[ -f $configtracker ]]; then
    sys_time_s=$(date +%s) 
    modify_time_s=$(stat -c %Y $configtracker)
    diff_day=$(( ($sys_time_s - $modify_time_s) / 86400 ))
    if [[ $diff_day -ge 7 ]]; then
        read -r -p "BT tracker file is too old, update? [yN] " answer
        if [[ "$answer" == "y" ]]; then
            run_tracker_update
        fi
    fi
else
    read -r -p "BT tracker file is not exist, update? [yN] " answer
    if [[ "$answer" == "y" ]]; then
        run_tracker_update
    fi
fi
if [[ -f $configtracker ]]; then
    config_cfg="--conf-path='$configtracker'"
fi

# resume ?
save_session="$dir/$session"
if [[ -s $save_session && ! -z "$dlthing" ]]; then
    echo "$save_session:"
    echo "===================="
    cat "$save_session"
    echo "===================="
    echo ""
    read -r -p "There are unfinished tasks, ignore those? [yN] " answer
    if [[ "$answer" != "y" ]]; then
        echo -e "\e[32mPlease use UI to add this task: $dlthing\e[0m"
        echo -e "\e[32mNow resume unfinished tasks!\e[0m"
        dlthing=""
    fi
fi

# input file
if [[ -z "$dlthing" ]]; then
    if [[ -s $save_session && -z "$ignore_unfinished" ]]; then
        inputfile_cfg="--input-file='$save_session'"
    fi
elif [[ -f "$dlthing" && "$dlthing" != *.torrent ]]; then
    inputfile_cfg="--input-file='$dlthing'"
    dlthing=""
fi

# create command
cmd="aria2c --dir='$dir' --save-session='$save_session' $config_cfg $max_con_per_server_cfg $misc_cfg"
if [[ -z "$dlthing" ]]; then
    cmd="$cmd $inputfile_cfg"
else
    cmd="$cmd '$dlthing'"
fi

# execute
echo "####################"
echo "$cmd" | sed -e 's/ \+$//g' -e 's/ \+/\n/g'
echo "####################"
eval "$cmd"

