#!/usr/bin/bash

while (($#!=0))
do
    string=$(dumpbin /HEADERS $1 | awk "
        /machine \(/{
            if (\$3==\"(x64)\")
                color = \"\\\\e[35m\";
            else
                color = \"\";
            print color \$3 \": $1\" \"\\\\e[0m\";
        }")
    if [ "$string" != "" ]; then
        echo -e $string
    fi
    shift
done

