#!python3

#
# Find something in system PATH
#
# usage: find_in_path something

import os
import re
import sys

def contains_msvcr_lib(folder, finder):
    try:
        for item in os.listdir(folder):
            if re.search(r'{}'.format(finder), item):
                return item
    except:
        pass
    return None

path = os.environ['PATH'].split(':')
for folder in path:
    finder = contains_msvcr_lib(folder, sys.argv[1])
    if finder != None:
        print("{}: \t{}".format(finder, folder))

