#!/bin/bash

params='-speed 6000 -port 2331 -if SWD -nolocalhostonly -nologtofile -nohalt -nosilent -vd -noir'  #-select usb=20151001

# Segger Jlink GDB Server
if [[ "$OSTYPE" =~ "cygwin" ]]; then
    JLinkGDBServerCL $params
elif [[ "$OSTYPE" =~ "linux" ]]; then
    JLinkGDBServer $params
fi

