#!/bin/bash

restartfile="/tmp/RESTART-JLinkGDBServer"
device="Cortex-M3"
speed="auto"
rtos=""

# Parse argument
for i in "$@"
do
    case $i in
        -h|--help)
            echo "gdbserver with jLink"
            echo "  gdbserver-jlink:           device=$device, speed=$speed"
            echo "  gdbserver-jlink Cortex-M4: device=Cortex-M4, speed=$speed"
            echo "  gdbserver-jlink 2000:      device=$device, speed=2000kHz"
            echo "Supported Devices: https://www.segger.com/jlink_supported_devices.html"
            exit 0
            ;;

        -f|--force) force_startup=1 ;;
        -r|--restart) restartit=1 ;;
        -p|--port) port=1 ;;

        --embos)    rtos="-rtos GDBServer/RTOSPlugin_embOS" ;;
        --freertos) rtos="-rtos GDBServer/RTOSPlugin_FreeRTOS" ;;
        --chibios)  rtos="-rtos GDBServer/RTOSPlugin_ChibiOS" ;;

        *)
            if [[ "$(echo $i | awk '/^[0-9]+$/')" == "$i" ]]; then
                speed="$i"
            else
                device="$i"
            fi
            ;;
    esac
done

# restart
if [[ -n "$restartit" ]]; then
    touch "$restartfile"
    exit
fi

# check process
if [[ -n "$force_startup" ]]; then
    jlinkpid=$(pgrep -i JLinkGDBServer)
    if [[ -n "$jlinkpid" ]]; then
        echo "JLinkGDBServer is already running! Kill It!"
        kill $jlinkpid
        wait $jlinkpid
        echo ""
    fi
fi

# add device Cortex-CM3, jlinkGdbServer will wait chip wakeuped, and then connect
params="-device $device -speed $speed -port 2331 -if SWD -nolocalhostonly -nologtofile -halt -nosilent -vd -noir -notimeout $rtos"  #-select usb=20151001

# Segger Jlink GDB Server
if [[ "$OSTYPE" =~ "cygwin" ]]; then
    gdbserver=JLinkGDBServerCL
elif [[ "$OSTYPE" =~ "linux" ]]; then
    kernel=$(uname -r)
    # WSL
    if [[ "$kernel" =~ "Microsoft" ]]; then
        gdbserver=JLinkGDBServerCL.exe
    else
        gdbserver=JLinkGDBServer
    fi
fi

# run
$gdbserver $params &
jlinkpid=$!

# catch interrupt
trap "kill $jlinkpid 2>/dev/null; wait $jlinkpid 2>/dev/null; exit" HUP INT QUIT ABRT TERM

# check restart
rm -f "$restartfile"
while true; do
    if [[ -f "$restartfile" ]]; then
        rm -f "$restartfile"
        echo -e "\n\n\e[31mRestart JLinkGDBServer!\e[0m\n\n"

        kill $jlinkpid
        wait $jlinkpid
        sleep 0.1

        $gdbserver $params &
        jlinkpid=$!
    fi

    sleep 0.1
done

