#!/bin/bash

stash_push_opt='--include-untracked'

if [[ "$1" == "-d" || "$1" == "-D" ]]; then
    delete_branch="$1"
    shift
elif [[ "$1" == "-a" ]]; then
    stash_push_opt="--all"
    shift
fi

if [[ -z "$1" || ! -z "$2" ]]; then
    echo "Switch branch and auto stash push/pop all modified and untracked files"
    echo "Usage: git bb [-d][-D][-a] [branch]"
    echo "Branchs: $(git branch --color=always | tr -d '\n' | sed 's/\*/  */g')"
    exit 1
fi

branch=$1
message="SWITCH-BRANCH-AUTO-WIP"

# Check branch whether is valid
if ! git branch | grep -q "^\\s*$branch$"; then
    echo "No such branch or in it!"
    echo "Branchs: $(git branch --color=always | tr -d '\n' | sed 's/\*/  */g')"
    exit 1
fi

# delete branch and its stash
if [[ ! -z "$delete_branch" ]]; then
    if git branch "$delete_branch" "$branch"; then
        # delete the stashed files
        stash=$(git stash list | awk -F: "/On $branch: $message/{print \$1}")
        if [[ ! -z "$stash" ]]; then
            git stash drop "$stash"
        fi
    fi
    exit 0
fi

# Stash files
git stash push "$stash_push_opt" -m "$message"

# Switch branch
git checkout "$branch"

# Pop the stashed files
stash=$(git stash list | awk -F: "/On $branch: $message/{print \$1}")
if [[ ! -z "$stash" ]]; then
    git stash pop "$stash"
fi

