#!/bin/bash

#
# hexdiff by liqinag
#

# exit if any errors
set -e

# check param
if [ $# != 2 ]; then
    echo "hexdiff: please give 2 param!"
    exit 1
fi

# tempfile
a=$(mktemp).a
b=$(mktemp).b

# hexdump
hexdump -v -C $1 >$a
hexdump -v -C $2 >$b

# diff
diff -u --color=auto $a $b

# remove temp file
rm -rf $a $b

