#! bash


# Cygwin
if [[ "$OSTYPE" =~ "cygwin" ]]; then
    cmd /c chcp 437 >/dev/null
    wmic path win32_pnpentity get caption /format:list | LC_ALL=C awk -e '/COM[0-9]/{match($0,/COM[0-9]+/);ttys=substr($0,RSTART+3,RLENGTH-3); name=substr($0,9,RSTART-9-2); printf "\033[33m/dev/ttyS%-2d \033[34mCOM%-2d\033[0m (%s)\n",ttys-1,ttys,name}'

# linux
elif [[ "$OSTYPE" =~ "linux" ]]; then
    ls /dev/ttyS*

fi

