#! bash

# show support baudrate
if [[ -n "$1" ]]; then
    for bauds in $(
        sed -r 's/^#define\s+B([1-9][0-9]+)\s+.*/\1/p;d' < \
            /usr/include/asm-generic/termbits.h ) ;do
        echo $bauds
        stty -F $1 $bauds && echo Ok.
    done  2>&1 |
        pr -at2
    exit
fi

# Cygwin
if [[ "$OSTYPE" =~ "cygwin" ]]; then
    cmd /c chcp 437 >/dev/null
    wmic path win32_pnpentity get caption /format:list | LC_ALL=C awk -e '/COM[0-9]/{match($0,/COM[0-9]+/);ttys=substr($0,RSTART+3,RLENGTH-3); name=substr($0,9,RSTART-9-2); printf "\033[33m/dev/ttyS%-2d \033[34mCOM%-2d\033[0m (%s)\n",ttys-1,ttys,name}' | sort -n

# WSL
elif [[ -n "$WSL_DISTRO_NAME" ]]; then
    wmic.exe path win32_pnpentity get caption /format:list | LC_ALL=C awk -e '/COM[0-9]/{match($0,/COM[0-9]+/);ttys=substr($0,RSTART+3,RLENGTH-3); name=substr($0,9,RSTART-9-2); printf "\033[33m/dev/ttyS%-2d \033[34mCOM%-2d\033[0m (%s)\n",ttys,ttys,name}' | sort -n

# linux
elif [[ "$OSTYPE" =~ "linux" ]]; then
    ls /dev/ttyS*

else
    echo "Not support OS!"

fi

