#!/bin/bash

#
# New a new bash
#
# Only for cygwin
#

# default window mode is normal
window=''

# check $PATH
if [[ "$PATH" != /bin:* ]]; then
    PATH="/bin:$PATH"
fi

# parse params
for i in "$@"; do
    case "$i" in
        -n) export NOTMUX=1; touch /tmp/.notmux.tmp; shift ;;
        -a) export NOTMUX=1; touch /tmp/.notmux.tmp; administrator=1; shift ;;
        -m) window='--window max'; shift ;;
        -s) slash=1; shift ;;
        *)  break ;;
    esac
done

# $TMUX env may lead some strange thing
unset TMUX
unset TMUX_PANE

# Keep PWD
export CHERE_INVOKING=1

# Execute the param
cmds="$@"
if [[ -n "$slash" ]]; then
    cmds="${cmds//\\/\\\\}"
fi
echo "$cmds" > /tmp/.init.tmp

# Start new window
if [[ "$OSTYPE" == "cygwin" ]]; then
    cygstart -w --action=open mintty $window --exec "$SHELL" --login -i
    #cmd /C start /I /B "$(cygpath -w -a /bin/mintty)" -

elif [[ -n "$WSL_DISTRO_NAME" ]]; then
    userprofile="$(cmd.exe /c "<nul set /p=%USERPROFILE%" 2>/dev/null)"
    appdata="$(cmd.exe /c "<nul set /p=%APPDATA%" 2>/dev/null)"
    localappdata="$(cmd.exe /c "<nul set /p=%LOCALAPPDATA%" 2>/dev/null)"
    if [[ -n "$administrator" ]]; then
        elevate="ELEVATE"
    else
        elevate="NOELEVATE"
    fi
    hstart.exe /$elevate "$localappdata\\wsltty\\bin\\mintty.exe $window --WSL=$WSL_DISTRO_NAME --configdir=$appdata\\wsltty --icon=$localappdata\\wsltty\\wsl.ico --exec $SHELL --login -i"
else
    echo "Not support OS!"
    exit 1
fi

