#!/bin/bash

# remove -* param
for i in "$@"; do
    case $i in
        -*) shift ;;
        *) break ;;
    esac
done

# check param
if [ $# -gt 1 ]; then
    echo "open: too many params: '$*'"
    exit 1
fi

path=${1:-"."}

if [[ "$OSTYPE" == "cygwin" ]]; then
    if [ -e "$path" ]; then
        path="$(cygpath -a -w "$path")"
    fi
    export HOME="$(cygpath -m --mydocs)/../"
    explorer "$path"

elif [[ -n "$WSL_DISTRO_NAME" ]]; then
    if [ -e "$path" ]; then
        path="$(wslpath -a -w "$path")"
    fi
    wslview "$path"

elif command -v xdg-open > /dev/null 2>&1; then
    xdg-open "$path"

else
    echo "Not support OS!"
    exit 1
fi

