#!/bin/bash

# check param
if [ $# -gt 1 ]; then
    echo "open: too many params!"
    exit 1
fi

path=${1:-"."}

if [[ "$OSTYPE" == "cygwin" ]]; then
    if [ -e "$path" ]; then
        path=$(cygpath --absolute --windows "$path")
    fi
    export HOME="$(cygpath -m --mydocs)/../"
    explorer "$path"

elif [[ -n "$WSL_DISTRO_NAME" ]]; then
    wslview "$path"

elif command -v xdg-open > /dev/null 2>&1; then
    xdg-open "$path"

else
    echo "Not support OS!"
    exit 1
fi

