#!/bin/bash

# check param
if [ $# -gt 1 ]; then
    echo "open: too many params!"
    exit 1
fi

path=${1:-"."}

os=$(uname -o)
if [ "$os" == "Cygwin" ]; then
    if [ -e "$path" ]; then
        path=$(cygpath --absolute --windows "$path")
    fi
    export HOME="$(cygpath -m --mydocs)/../"
    explorer "$path"
    exit 0
else
    xdg-open "$path"
    exit 0
fi

echo "open: unsupport os type: $os"
exit 1

