#!/bin/bash

# read stdin
IFS='' read -d '' -r input

# put it to clipboard
if [[ "$OSTYPE" =~ "cygwin" ]]; then
    echo -n "$input" >/dev/clipboard
elif [[ "$OSTYPE" =~ "linux" ]]; then
    kernel=$(uname -r)
    if [[ "$OSTYPE" =~ "Microsoft" ]]; then
        echo -n "$input" | clip.exe
    else
        echo -n "$input" | xclip
    fi
fi

