#!/bin/bash

# put it to clipboard
if [[ "$OSTYPE" =~ "cygwin" ]]; then
    cat /dev/clipboard
elif [[ "$OSTYPE" =~ "linux" ]]; then
    kernel=$(uname -r)
    if [[ "$kernel" =~ "Microsoft" ]]; then
        clip.exe -o
    else
        xclip -o
    fi
fi

