#!/bin/bash

privoxy_config='/etc/privoxy/config'
gfwlist_action='gfwlist.action'
socks_proxy='127.0.0.1:1080'
http_proxy='127.0.0.1:8118'

gen_pac=0
pac=0
global=0

# Parse argument
for i in "$@"
do
    case $i in
        -x|--gen-pac)
            gen_pac=1
            shift
            ;;
        -p|--pac)
            pac=1
            shift
            ;;
        -g|--global)
            global=1
            shift
            ;;
        -h|--help)
            echo "by liqiang"
            exit 0
            ;;
        *)
            # unknown option
        ;;
    esac
done

# generate PAC
if [[ "$gen_pac" == "1" ]]; then
    echo "Generate privoxy.action from gfwlist.txt ..."
    gfwlist2privoxy $socks_proxy >/dev/null
    mv -f $gfwlist_action /etc/privoxy
fi

if [[ "$pac" == "1" ]]; then
    \grep "^actionsfile $gfwlist_action" $privoxy_config >/dev/null || echo "actionsfile $gfwlist_action" >>$privoxy_config
    sed -i "/^forward-socks5 \/ $socks_proxy ./d" $privoxy_config >/dev/null
fi

if [[ "$global" == "1" ]]; then
    \grep "^forward-socks5 / $socks_proxy ." $privoxy_config >/dev/null || echo "forward-socks5 / $socks_proxy ." >>$privoxy_config
    sed -i "/^actionsfile $gfwlist_action/d" $privoxy_config >/dev/null
fi

echo "HTTP: $http_proxy"
echo "SOCKS: $socks_proxy"

# privoxy
privoxy --no-daemon $privoxy_config

## privoxy listen 8118 port
#proxy="http://127.0.0.1:8118"
#export http_proxy=$proxy
#export https_proxy=$proxy
#export no_proxy="localhost, 127.0.0.1, ::1"

