#!/bin/bash
######################################################################
# @file proxy
# @date 2018/11/19 22:57:47
# @author liqiang
#
# Easy to use privoxy
#   1. HTTP to SOCKS
#   2. System PAC/GLOBAL proxy
#   3. Generate PAC file from gfwlist
#
# privoxy: http://www.privoxy.org/
#
######################################################################

privoxy_config_dir="/etc/privoxy"
privoxy_config="$privoxy_config_dir/config"
gfwlist_action="gfwlist.action"
gfwlist_config="$privoxy_config_dir/$gfwlist_action"

gen_pac=0
pac_proxy=0
global_proxy=0
redo_http_listen=0
redo_socks_forward=0
pre_pac_enable=0
system_proxy=0
daemon_mode=0

# sudo
if [[ "$OSTYPE" != "cygwin" ]]; then
    if [[ "$EUID" != "0" ]]; then
        sudo $0 $@
        exit
    fi
fi

# Get socks and http address
get_address ()
{
    pre_pac_enable=0
    http_listen=$(awk '/^listen-address/{print $2}' $privoxy_config)
    socks_forward=$(awk '/^forward-socks5 \//{print $3}' $privoxy_config)

    if [[ -z $socks_forward ]]; then
        if [[ -f "$gfwlist_config" ]]; then
            socks_forward=$(awk '/{\+forward-override{forward-socks5/{print $2}' $gfwlist_config)
            if [[ ! -z $socks_forward ]]; then
                pre_pac_enable=1
            fi
        fi
    fi

    if [[ -z $http_listen ]]; then
        http_listen='127.0.0.1:8118'
    fi

    if [[ -z $socks_forward ]]; then
        socks_forward='127.0.0.1:1080'
    fi
}

# Get address
get_address

# Parse argument
for i in "$@"
do
    case $i in
        -l=*|--listen-http=*)
            http_listen="${i#*=}"
            redo_http_listen=1
            shift
            ;;
        -f=*|--forward-socks=*)
            socks_forward="${i#*=}"
            redo_socks_forward=1
            shift
            ;;
        -x|--gen-pac)
            gen_pac=1
            shift
            ;;
        -p|--pac)
            pac_proxy=1
            shift
            ;;
        -g|--global)
            global_proxy=1
            shift
            ;;
        -s|--sys)
            system_proxy=1
            shift
            ;;
        -d|--daemon)
            daemon_mode=1
            shift
            ;;
        -k|--kill)
            killall privoxy
            sysproxy.exe off
            exit 0
            shift
            ;;
        -h|--help)
            echo "Easy to use proxy"
            echo "Usage:"
            echo "  -l|--listen-http   Set listen HTTP address (127.0.0.1:8118)"
            echo "  -f|--forward-socks Set forward SOCKS address (127.0.0.1:1080)"
            echo "  -x|--gen-pac       Generate PAC"
            echo "  -p|--pac           PAC proxy mode"
            echo "  -g|--global        Global proxy mode"
            echo "  -s|--sys           system proxy"
            echo "  -d|--daemon        run as daemon"
            echo "  -k|--kill          kill the daemon process and clear"
            echo "  -h|--help          Show this help"
            echo "by liqiang"
            exit 0
            ;;
        *)
            # unknown option
        ;;
    esac
done

# generate PAC
if [[ "$gen_pac" == "1" ]]; then
    echo "Generate privoxy.action from gfwlist.txt ..."
    gfwlist2privoxy $socks_forward >/dev/null
    if [[ "$?" == "0" ]]; then
        mv -f $gfwlist_action $privoxy_config_dir
    else
        exit 1
    fi
fi

# Use PAC
if [[ "$pac_proxy" == "1" ]]; then
    sed -i "/^forward-socks5 \//d" $privoxy_config
    sed -i "/^actionsfile $gfwlist_action/d" $privoxy_config
    echo "actionsfile $gfwlist_action" >>$privoxy_config
fi

# Use global
if [[ "$global_proxy" == "1" ]]; then
    sed -i "/^forward-socks5 \//d" $privoxy_config
    sed -i "/^actionsfile $gfwlist_action/d" $privoxy_config
    echo "forward-socks5 / $socks_forward ." >>$privoxy_config
fi

# reset http listen address
if [[ "$redo_http_listen" == "1" ]]; then
    sed -i "/^listen-address /d" $privoxy_config
    echo "listen-address $http_listen" >>$privoxy_config
fi

# reset socks socks address
if [[ "$redo_socks_forward" == "1" ]]; then
    sed -i "s/^forward-socks5 \/ .\+$/forward-socks5 \/ $socks_forward ./" $privoxy_config
    if [[ -f "$gfwlist_config" ]]; then
        sed -i "s/^{+forward-override{forward-socks5 .\+$/{+forward-override{forward-socks5 $socks_forward .}}/" $gfwlist_config
    fi
fi

# show
get_address
if [[ "$pre_pac_enable" == "1" ]]; then
    echo -e "\e[32mPAC Mode\e[0m"
else
    echo -e "\e[32mGLOBAL Mode\e[0m"
fi
echo -e "\e[32mListen HTTP: $http_listen\e[0m"
echo -e "\e[32mForward SOCKS5: $socks_forward\e[0m"

# open system proxy
if [[ "$system_proxy" == "1" ]]; then
    echo -e "\e[32mSystem proxy running\e[0m"
    sysproxy.exe global $http_listen
fi

if [[ "$daemon_mode" == "1" ]]; then
    # privoxy
    privoxy $privoxy_config
else
    # catch interrupt
    trap 'echo -e "\e[31minterrupt\e[0m"' HUP INT QUIT ABRT TERM

    # privoxy
    privoxy --no-daemon $privoxy_config

    # close system proxy
    if [[ "$system_proxy" == "1" ]]; then
        # close system proxy
        sysproxy.exe off
    fi
fi

## privoxy listen 8118 port
#proxy="http://127.0.0.1:8118"
#export http_proxy=$proxy
#export https_proxy=$proxy
#export no_proxy="localhost, 127.0.0.1, ::1"

