#!/bin/bash

privoxy_config_dir='/etc/privoxy'
privoxy_config=$privoxy_config_dir'/config'
gfwlist_action='gfwlist.action'

gen_pac=0
pac_proxy=0
global_proxy=0
redo_http_listen=0
redo_socks_forward=0
pre_pac_enable=0

get_address ()
{
    http_listen=$(awk '/^listen-address/{print $2}' $privoxy_config)
    socks_forward=$(awk '/^forward-socks5 \//{print $3}' $privoxy_config)

    if [[ -z $socks_forward ]]; then
        if [[ -f "$privoxy_config_dir/$gfwlist_action" ]]; then
            socks_forward=$(awk '/{\+forward-override{forward-socks5/{print $2}' $privoxy_config_dir/$gfwlist_action)
            if [[ ! -z $socks_forward ]]; then
                pre_pac_enable=1
            fi
        fi
    fi

    if [[ -z $socks_forward ]]; then
        socks_proxy='127.0.0.1:1080'
    fi
}

get_address

# Parse argument
for i in "$@"
do
    case $i in
        -l=*|--listen-http=*)
            http_listen="${i#*=}"
            redo_http_listen=1
            shift
            ;;
        -f=*|--forward-socks=*)
            socks_forward="${i#*=}"
            redo_socks_forward=1
            shift
            ;;
        -x|--gen-pac)
            gen_pac=1
            shift
            ;;
        -p|--pac)
            pac_proxy=1
            shift
            ;;
        -g|--global)
            global_proxy=1
            shift
            ;;
        -h|--help)
            echo "by liqiang"
            exit 0
            ;;
        *)
            # unknown option
        ;;
    esac
done

if [[ "$redo_socks_forward" == "1" ]]; then
    if [[ "$pac_proxy" == "1" ]]; then
        gen_pac=1
    fi
    if [[ "$pac_proxy" != "1" && "$global_proxy" != "1" ]]; then
        if [[ "$pre_pac_enable" == "1" ]]; then
            pac_proxy=1
            gen_pac=1
        else
            global_proxy=1
        fi
    fi
fi

# generate PAC
if [[ "$gen_pac" == "1" ]]; then
    echo "Generate privoxy.action from gfwlist.txt ..."
    gfwlist2privoxy $socks_forward >/dev/null
    if [[ "$?" == "0" ]]; then
        mv -f $gfwlist_action $privoxy_config_dir
    else
        exit 1
    fi
fi

if [[ "$pac_proxy" == "1" ]]; then
    sed -i "/^forward-socks5 \//d" $privoxy_config
    sed -i "/^actionsfile $gfwlist_action/d" $privoxy_config
    echo "actionsfile $gfwlist_action" >>$privoxy_config
fi

if [[ "$global_proxy" == "1" ]]; then
    sed -i "/^forward-socks5 \//d" $privoxy_config
    sed -i "/^actionsfile $gfwlist_action/d" $privoxy_config
    echo "forward-socks5 / $socks_forward ." >>$privoxy_config
fi

if [[ "$redo_http_listen" == "1" ]]; then
    sed -i "/^listen-address /d" $privoxy_config
    echo "listen-address $http_listen" >>$privoxy_config
fi

get_address
echo "HTTP: $http_listen"
echo "SOCKS: $socks_forward"

# privoxy
privoxy --no-daemon $privoxy_config

## privoxy listen 8118 port
#proxy="http://127.0.0.1:8118"
#export http_proxy=$proxy
#export https_proxy=$proxy
#export no_proxy="localhost, 127.0.0.1, ::1"

