#!/bin/bash

#
# For cygwin QR generate
#

# check param
if [ $# != 1 ]; then
    echo "showqr: please give 1 param!"
    exit 1
fi

# check os
os=$(uname -o)
if [ "$os" == "Cygwin" ]; then
    # pic
    pic="/tmp/qr.tmp.png"

    # qrencode
    qrencode -o $pic "$1"

    # open the picture
    open $pic

    # exit successfully
    exit 0
fi

echo "showqr: unsupport os: $os"
exit 1

