#!/bin/bash

######################################################################
# @file ss
# @brief auto sslocal
# @date 2017/2/28 22:57:47
# @author liqiang
#
# 127.0.0.1:1080 will be as the proxy server
#
# In chrome, use SwitchyOmega plugin to proxy (socks5)
#
# @addtogroup 
# @ingroup 
# @details 
#
# @{
######################################################################

pic='/tmp/ssqr.png'

global_proxy=0
i=0

if [ ! -z $1 ]; then
    if [ "$1" == "-g" ]; then
        global_proxy=1
        if [ ! -z $2 ]; then
            i=$2
        fi
    else
        i=$1
    fi
fi

res=( \
    http://free.shadowsocks8.cc/images/server01.png \
    http://free.shadowsocks8.cc/images/server02.png \
    http://free.shadowsocks8.cc/images/server03.png \
    http://abc.ishadow.online/img/qr/sga.png \
    http://abc.ishadow.online/img/qr/sgb.png \
    http://abc.ishadow.online/img/qr/sgc.png \
    http://abc.ishadow.online/img/qr/usa.png \
    http://abc.ishadow.online/img/qr/usb.png \
    http://abc.ishadow.online/img/qr/usc.png \
    http://abc.ishadow.online/img/qr/jpa.png \
    http://abc.ishadow.online/img/qr/jpb.png \
    http://abc.ishadow.online/img/qr/jpc.png \
    )

if [ "$i" -ge "${#res[*]}" ]; then
    echo "ss: invalid index"
    exit 1
fi

wget "${res[$i]}" -O $pic
if [ $? != 0 ]; then
    exit 1
fi

# like: rc4-md5:52918214@138.68.61.42:23456
serverinfo=$(zbarimg -q --raw $pic | sed 's#^ss://##' | base64 -d)

# link: -m rc4-md5 -k 52918214 -s 138.68.61.42 -p 23456
serverparam=$(echo $serverinfo | sed 's/^/-m /; s/:/ -k /; s/@/ -s /; s/:/ -p /')

localparam='-b 127.0.0.1 -l 1080'

echo -e "\e[31mServer: $serverinfo\e[0m"
echo -e "\e[31mProxy: 127.0.0.1:1080\e[0m"

if [ $global_proxy -eq 1 ]; then
    # open system proxy
    echo "System proxy running"
    sysproxy global 127.0.0.1:1080
fi

# catch interrupt
trap 'echo "interrupt"' HUP INT QUIT ABRT TERM

# ss
shadowsocks --http-proxy -t 600 $localparam $serverparam

if [ $global_proxy -eq 1 ]; then
    # close system proxy
    sysproxy off
fi

# @} #

