#!/usr/bin/env bash
#
# Simple todo list manager.
#
# Tasks will be written to ~/tasks.
# Finished tasks, plus a timestamp, will be written to ~/tasks.log.
#
# usage: task [-e] [-f [line]]
#
#   task        list tasks
#   task ...    add task
#   task -e     edit tasks using $EDITOR
#   task -f 3   finish task on line 3
#   task 3      finish task on line 3
#   task -f     finish all tasks
#

task_exists() {
    if [[ -s ~/tasks ]]; then
        newline="$*"
        while read -r line; do
            if [[ "$line" == "$newline" ]]; then
                return 0
            fi
        done < ~/tasks
    fi
    return 1
}

task() {
    if (( $# )); then
        if [[ "$@" =~ ^[0-9]+$ ]]; then
            finish "$@"
        elif task_exists "$@"; then
            echo "Task exists already."
        else
            echo "$@" >> ~/tasks
        fi
    else
        if [[ -s ~/tasks ]]; then
            nl -w2 -s'  ' ~/tasks
        else
            echo -e "\e[1mLAZY TIME\e[0m"
        fi
    fi
}

finish() {
    if (( $# == 0 )); then
        read -p "Really? [yN] " answer
        [[ "$answer" != y ]] && return
    fi
    line="$(2>/dev/null sed -i '' -e "${1}w /dev/stdout" -e "${1}d" ~/tasks)"
    if [[ -n $line ]]; then
        while IFS= read -r task; do
            echo "$(date +'%F %R') $task" >> ~/tasks.log
            echo "[FINISH] $task"
        done <<< "$line"
    fi
}

case "$1" in
    -h|--help)
        echo "Usage: task [-e] [-f] task_desc"
        ;;
    -e)
        $EDITOR ~/tasks
        ;;
    -f)
        shift
        finish "$@"
        ;;
    *)
        task "$@"
        ;;
esac
