#!/bin/bash
######################################################################
# @file dl
# @brief 
# @date Thu, Dec 20, 2018  5:34:20 PM
# @author liqiang
######################################################################
#
# 北京邮电大学TV
# http://ivi.bupt.edu.cn/
#
# 湖南卫视FHD,http://183.251.61.207/PLTV/88888888/224/3221225827/index.m3u8

declare -A TVs

TVs=( \
  ['CCTV1']='http://183.251.61.207/PLTV/88888888/224/3221225922/index.m3u8' \
  ['CCTV3']='http://183.251.61.207/PLTV/88888888/224/3221225801/index.m3u8' \
  ['CCTV5']='http://183.251.61.207/PLTV/88888888/224/3221225925/index.m3u8' \
  ['CCTV6']='http://183.251.61.207/PLTV/88888888/224/3221225804/index.m3u8' \
  ['CCTV8']='http://183.251.61.207/PLTV/88888888/224/3221225806/index.m3u8' \
  ['BTV']='rtsp://119.39.49.116:554/ch00000090990000001077.sdp?vcdnid=001' \
  ['HNTV']='rtsp://119.39.49.116:554/ch00000090990000001079.sdp?vcdnid=001' \
  ['CCTV1高清']='http://ivi.bupt.edu.cn/hls/cctv1hd.m3u8' \
  ['CCTV3高清']='http://ivi.bupt.edu.cn/hls/cctv3hd.m3u8' \
  ['CCTV5+高清']='http://ivi.bupt.edu.cn/hls/cctv5phd.m3u8' \
  ['CCTV6高清']='http://ivi.bupt.edu.cn/hls/cctv6hd.m3u8' \
  ['CCTV8高清']='http://ivi.bupt.edu.cn/hls/cctv8hd.m3u8' \
  ['CHC高清电影']='http://ivi.bupt.edu.cn/hls/chchd.m3u8' \
  ['北京卫视高清']='http://ivi.bupt.edu.cn/hls/btv1hd.m3u8' \
  ['北京文艺高清']='http://ivi.bupt.edu.cn/hls/btv2hd.m3u8' \
  ['北京纪实高清']='http://ivi.bupt.edu.cn/hls/btv11hd.m3u8' \
  ['湖南卫视高清']='http://ivi.bupt.edu.cn/hls/hunanhd.m3u8' \
  ['浙江卫视高清']='http://ivi.bupt.edu.cn/hls/zjhd.m3u8' \
  ['江苏卫视高清']='http://ivi.bupt.edu.cn/hls/jshd.m3u8' \
  ['东方卫视高清']='http://ivi.bupt.edu.cn/hls/dfhd.m3u8' \
  ['安徽卫视高清']='http://ivi.bupt.edu.cn/hls/ahhd.m3u8' \
  ['黑龙江卫视高清']='http://ivi.bupt.edu.cn/hls/hljhd.m3u8' \
  ['辽宁卫视高清']='http://ivi.bupt.edu.cn/hls/lnhd.m3u8' \
  ['深圳卫视高清']='http://ivi.bupt.edu.cn/hls/szhd.m3u8' \
  ['广东卫视高清']='http://ivi.bupt.edu.cn/hls/gdhd.m3u8' \
  ['天津卫视高清']='http://ivi.bupt.edu.cn/hls/tjhd.m3u8' \
  ['湖北卫视高清']='http://ivi.bupt.edu.cn/hls/hbhd.m3u8' \
  ['山东卫视高清']='http://ivi.bupt.edu.cn/hls/sdhd.m3u8' \
  ['重庆卫视高清']='http://ivi.bupt.edu.cn/hls/cqhd.m3u8' \
  ['CCTV1综合']='http://ivi.bupt.edu.cn/hls/cctv1.m3u8' \
  ['CCTV2财经']='http://ivi.bupt.edu.cn/hls/cctv2.m3u8' \
  ['CCTV3综艺']='http://ivi.bupt.edu.cn/hls/cctv3.m3u8' \
  ['CCTV4中文国际']='http://ivi.bupt.edu.cn/hls/cctv4.m3u8' \
  ['CCTV6电影']='http://ivi.bupt.edu.cn/hls/cctv6.m3u8' \
  ['CCTV7军事农业']='http://ivi.bupt.edu.cn/hls/cctv7.m3u8' \
  ['CCTV8电视剧']='http://ivi.bupt.edu.cn/hls/cctv8.m3u8' \
  ['CCTV9纪录']='http://ivi.bupt.edu.cn/hls/cctv9.m3u8' \
  ['CCTV10科教']='http://ivi.bupt.edu.cn/hls/cctv10.m3u8' \
  ['CCTV11戏曲']='http://ivi.bupt.edu.cn/hls/cctv11.m3u8' \
  ['CCTV12社会与法']='http://ivi.bupt.edu.cn/hls/cctv12.m3u8' \
  ['CCTV13新闻']='http://ivi.bupt.edu.cn/hls/cctv13.m3u8' \
  ['CCTV14少儿']='http://ivi.bupt.edu.cn/hls/cctv14.m3u8' \
  ['CCTV15音乐']='http://ivi.bupt.edu.cn/hls/cctv15.m3u8' \
  ['CCTVNEWS']='http://ivi.bupt.edu.cn/hls/cctv16.m3u8' \
  ['北京卫视']='http://ivi.bupt.edu.cn/hls/btv1.m3u8' \
  ['北京文艺']='http://ivi.bupt.edu.cn/hls/btv2.m3u8' \
  ['北京科教']='http://ivi.bupt.edu.cn/hls/btv3.m3u8' \
  ['北京影视']='http://ivi.bupt.edu.cn/hls/btv4.m3u8' \
  ['北京财经']='http://ivi.bupt.edu.cn/hls/btv5.m3u8' \
  ['北京生活']='http://ivi.bupt.edu.cn/hls/btv7.m3u8' \
  ['北京青年']='http://ivi.bupt.edu.cn/hls/btv8.m3u8' \
  ['北京新闻']='http://ivi.bupt.edu.cn/hls/btv9.m3u8' \
  ['北京卡酷少儿']='http://ivi.bupt.edu.cn/hls/btv10.m3u8' \
  ['深圳卫视']='http://ivi.bupt.edu.cn/hls/sztv.m3u8' \
  ['安徽卫视']='http://ivi.bupt.edu.cn/hls/ahtv.m3u8' \
  ['河南卫视']='http://ivi.bupt.edu.cn/hls/hntv.m3u8' \
  ['陕西卫视']='http://ivi.bupt.edu.cn/hls/sxtv.m3u8' \
  ['吉林卫视']='http://ivi.bupt.edu.cn/hls/jltv.m3u8' \
  ['广东卫视']='http://ivi.bupt.edu.cn/hls/gdtv.m3u8' \
  ['山东卫视']='http://ivi.bupt.edu.cn/hls/sdtv.m3u8' \
  ['湖北卫视']='http://ivi.bupt.edu.cn/hls/hbtv.m3u8' \
  ['广西卫视']='http://ivi.bupt.edu.cn/hls/gxtv.m3u8' \
  ['河北卫视']='http://ivi.bupt.edu.cn/hls/hebtv.m3u8' \
  ['西藏卫视']='http://ivi.bupt.edu.cn/hls/xztv.m3u8' \
  ['内蒙古卫视']='http://ivi.bupt.edu.cn/hls/nmtv.m3u8' \
  ['青海卫视']='http://ivi.bupt.edu.cn/hls/qhtv.m3u8' \
  ['四川卫视']='http://ivi.bupt.edu.cn/hls/sctv.m3u8' \
  ['江苏卫视']='http://ivi.bupt.edu.cn/hls/jstv.m3u8' \
  ['天津卫视']='http://ivi.bupt.edu.cn/hls/tjtv.m3u8' \
  ['山西卫视']='http://ivi.bupt.edu.cn/hls/sxrtv.m3u8' \
  ['辽宁卫视']='http://ivi.bupt.edu.cn/hls/lntv.m3u8' \
  ['厦门卫视']='http://ivi.bupt.edu.cn/hls/xmtv.m3u8' \
  ['新疆卫视']='http://ivi.bupt.edu.cn/hls/xjtv.m3u8' \
  ['东方卫视']='http://ivi.bupt.edu.cn/hls/dftv.m3u8' \
  ['黑龙江卫视']='http://ivi.bupt.edu.cn/hls/hljtv.m3u8' \
  ['湖南卫视']='http://ivi.bupt.edu.cn/hls/hunantv.m3u8' \
  ['云南卫视']='http://ivi.bupt.edu.cn/hls/yntv.m3u8' \
  ['江西卫视']='http://ivi.bupt.edu.cn/hls/jxtv.m3u8' \
  ['福建东南卫视']='http://ivi.bupt.edu.cn/hls/dntv.m3u8' \
  ['浙江卫视']='http://ivi.bupt.edu.cn/hls/zjtv.m3u8' \
  ['贵州卫视']='http://ivi.bupt.edu.cn/hls/gztv.m3u8' \
  ['宁夏卫视']='http://ivi.bupt.edu.cn/hls/nxtv.m3u8' \
  ['甘肃卫视']='http://ivi.bupt.edu.cn/hls/gstv.m3u8' \
  ['重庆卫视']='http://ivi.bupt.edu.cn/hls/cqtv.m3u8' \
  ['兵团卫视']='http://ivi.bupt.edu.cn/hls/bttv.m3u8' \
  ['旅游卫视']='http://ivi.bupt.edu.cn/hls/lytv.m3u8' \
)

record_file_option=''
if [[ "$1" == "-r" ]]; then
    record_file_option="--record-file=mpv_record_$(date '+%Y%m%d_%H%M%S').ts"
    shift
fi

if [[ -n "$1" ]]; then
    TV=${TVs[$1]}
fi

if [[ -z "$TV" ]]; then
    echo "Options:"
    echo "-r  Record TV stream to file"
    echo ""
    echo "TVs:"
    echo "${!TVs[@]}" | sed 's/ /\n/g' | sort | fmt
    exit 1
fi

if [[ $OSTYPE == cygwin* ]]; then
    mpv $record_file_option $TV 2>&1 | stdbuf -o0 tr '\n' '\r'
else
    mpv $record_file_option $TV
fi

