#!/bin/bash

#
# For cygwin, wifi control
#

cmd /c chcp 437 >/dev/null

ssid="lqWIFI"
key="1234567890"

function usage()
{
    echo "wifi:"
    echo "    start:     Start WIFI AP"
    echo "    stop:      Stop WIFI AP"
    echo "    connect:   Connect to WIFI"
    echo "    disonnect: Disconnect from WIFI"
    echo "    delete:    Delete profile (wifi show profiles)"
    echo "    show:      Show all WLAN info"
    echo "    help:      Show me"
    echo ""
    echo "wifi show:"
    netsh wlan show '/?'
}

function gbk2utf8()
{
    iconv -f GBK -t UTF8
}

if [ $# == 0 ]; then
    ipconfig '/all' | gbk2utf8 | awk '/^\w/{h=1;hs=hsn;hsn=$0}; /^\s+\w/{bs=bs$0"\n"}; {if(h){if(!match(bs, "Media disconnected")){print hs;print bs}h=0;bs=""}}'
    netsh wlan show interfaces | gbk2utf8
    exit 1
fi

case $1 in
    "start")
        netsh wlan show driver | findstr Hosted
        echo "    --------------------------"
        netsh wlan set hostednetwork mode=allow ssid=$ssid key=$key
        netsh wlan start hostednetwork
        echo "ssid=$ssid key=$key"
        netsh wlan show hostednetwork
        ;;
    "stop")
        netsh wlan stop hostednetwork
        netsh wlan set hostednetwork mode=disallow
        netsh wlan show hostednetwork
        ;;
    "connect")
        netsh wlan connect "$2"
        ;;
    "disconnect")
        netsh wlan disconnect
        ;;
    "delete")
        while (($#!=1))
        do
            netsh wlan delete profile "$2"
            shift
        done
        ;;
    "show")
        if [[ "$2" ]]; then
            netsh wlan show "$2" | gbk2utf8
        else
            netsh wlan show all | gbk2utf8
        fi
        ;;
    *)
        usage
        ;;
esac

