#!/bin/bash

# var
input=''
execute=''
slash=''

function print_usage ()
{
    echo "Convert cygwin-string to windows-string and excute it"
    echo "Options:"
    echo "  -i <input>  convert input string"
    echo "  -e          execute it"
    echo "  -s          use slash(\\) instead of backslash(/)"
    echo "  -h          show this help and exit"
    echo "by liqiang (2018/06/06)"
    exit 1
}

# Parsing params
while getopts i:esh opt; do
    case $opt in
        i) input="$OPTARG" ;;
        e) execute=1 ;;
        s) slash=1 ;;
        ?) print_usage ;;
    esac
done

# check input
if [[ -z "$input" ]]; then
    # read stdin
    IFS='' read -d '' -r input

    # check
    if [[ -z "$input" ]]; then
        print_usage
    fi
fi

# cygwin dir keyword
user_dir=$(cygpath ~)       # /home/username
root_dir=$(cygpath -w / | sed 's#\\#/#g')    # /D:\cygwin64

# change
result=$(echo "$input" | sed "s#${user_dir}#${root_dir}${user_dir}#g; \
                              s#/cygdrive/\\([a-z]\\)#\\1:#g; \
                              s#~/#${root_dir}${user_dir}/#g;")

if [[ -n "$slash" ]]; then
    result=${result//\//\\\\} # $(echo "$result" | sed "s#/#\\\\\\\\#g")
fi

# excute
if [[ -n "$execute" ]]; then
#    echo "$result"
    eval "$result"
else
    echo "$result"
fi
