#!/bin/bash

# var
input=''
execute=''
slash=''
precise=''

function print_usage ()
{
    echo "Convert cygwin-string to windows-string and excute it"
    echo "Options:"
    echo "  -i <input>  convert input string"
    echo "  -e          execute it"
    echo "  -p          use cygpath to precise convert each exist paths"
    echo "  -s          use slash(\\) instead of backslash(/)"
    echo "  -h          show this help and exit"
    echo "by liqiang (2018/06/06)"
    exit 1
}

# Parsing params
while getopts i:eshp opt; do
    case $opt in
        i) input="$OPTARG" ;;
        e) execute=1 ;;
        p) precise=1 ;;
        s) slash=1 ;;
        ?) print_usage ;;
    esac
done

# check input
if [[ -z "$input" ]]; then
    # read stdin
    IFS='' read -d '' -r input

    # check
    if [[ -z "$input" ]]; then
        print_usage
    fi
fi

if [[ -n "$precise" ]]; then
    result=''
    for i in $input; do
        i=${i/\~/$HOME}
        if [[ -e "$i" ]]; then
            result="${result}$(cygpath -m $i) "
        else
            result="${result}${i} "
        fi
    done
else
    # cygwin dir keyword
    user_dir=$(cygpath ~)       # /home/username
    root_dir=$(cygpath -m /)    # D:/cygwin64
    # convert
    result=$(echo "$input" | sed "s#${user_dir}/#${root_dir}${user_dir}/#g; \
                                  s#/cygdrive/\\([a-z]\\)/#\\1:/#g; \
                                  s#~/#${root_dir}${user_dir}/#g; \
                                  s#\\(^\\|\\s\\|\"\\)/\\([A-Za-z0-9._-]\\+\\)/#\\1${root_dir}/\\2/#g")
fi

if [[ -n "$slash" ]]; then
    result=${result//\//\\\\} # $(echo "$result" | sed "s#/#\\\\\\\\#g")
fi

# excute
if [[ -n "$execute" ]]; then
#    echo "$result"
    eval "$result"
else
    echo "$result"
fi
