#!/usr/bin/env python3
######################################################################
# @file makekeil.py
# @brief 
# @date 2016/11/10 9:20:29
# @author liqiang
#
# @addtogroup 
# @ingroup 
# @details 
#
# @{
######################################################################

######################################################################
# IMPORT
######################################################################
import sys
import os
import time
import subprocess
import tempfile
import glob
import platform
import re

######################################################################
# VARIABLES
######################################################################
keilparams = {'make':'-j0 -b', 'clean':'-j0 -c', 'debug':'-d', 'download':'-f'}

keil_process = None
tail_process = None

uname = subprocess.getoutput("uname -a")
in_cygwin = re.search(r'cygwin', uname, re.I)
in_wsl    = re.search(r'microsoft', uname, re.I)

# make
# make flag
# make uvproj
# make uvproj flag
flag = 'make'
uvproj = '.'
paramnum = len(sys.argv)-1
if paramnum==0: # make
    pass
elif paramnum==1:
    if sys.argv[1] in keilparams: # make flag
        flag = sys.argv[1]
    else: # make uvproj
        uvproj = sys.argv[1]
else: # make uvproj flag
    uvproj = sys.argv[1]
    if sys.argv[2] in keilparams:
        flag = sys.argv[2]

if not os.path.exists(uvproj):
    print("[Error] Not exist this path: " + uvproj)
    sys.exit(-1)

uvproj = os.path.abspath(uvproj)
if os.path.isdir(uvproj):
    uvprojs = glob.glob(uvproj + '/*.uvproj')
    if len(uvprojs)==0:
        print("[Error] Not exist uvproj project: " + uvproj)
        sys.exit(-2)
    else:
        uvproj = uvprojs[0]

print('{}: {}'.format(flag, uvproj))
print('Entering directory: {}'.format(os.path.dirname(uvproj)))
sys.stdout.flush()

######################################################################
# FUNCTIONS
######################################################################


######################################################################
# MAIN
######################################################################

if in_wsl:
    # keil not support "\\wsl$\Ubuntu-18.04" path type
    tmpfilename_win = subprocess.getoutput('cmd.exe /c "<nul set /p=%TEMP%\\uv4_%RANDOM%.log" 2>/dev/null')
    tmpfilename = subprocess.getoutput("wslpath -u '{}'".format(tmpfilename_win))
    uvproj_win = subprocess.getoutput("wslpath -w '{}'".format(uvproj))
    open(tmpfilename, 'w').close()
else:
    tmpfilefd, tmpfilename = tempfile.mkstemp()
    os.close(tmpfilefd)
    if in_cygwin:
        uvproj_win = subprocess.getoutput("cygpath -w '{}'".format(uvproj))
        tmpfilename_win = subprocess.getoutput("cygpath -w '{}'".format(tmpfilename))
    else:
        uvproj_win = uvproj
        tmpfilename_win = tmpfilename

keil_process = subprocess.Popen('UV4.exe ' + keilparams[flag] + ' "' + uvproj_win + '" -o "' + tmpfilename_win + '"', shell=True)
tail_process = subprocess.Popen('tail -f ' + tmpfilename, shell=True)

while True:
    try:
        keil_process.wait()
        tail_process.kill()
        tail_process.wait()
        time.sleep(0.1)
        break

    except:
        try:
            keil_process.kill()
        except:
            pass

while True:
    if os.path.isfile(tmpfilename):
        try:
            os.unlink(tmpfilename)
        except:
            time.sleep(0.01)
            continue
    break

print('Leaving directory')
sys.stdout.flush()

# @} #

