#!/usr/bin/env python3
######################################################################
# @file makekeil.py
# @brief 
# @date 2016/11/10 9:20:29
# @author liqiang
#
# @addtogroup 
# @ingroup 
# @details 
#
# @{
######################################################################

######################################################################
# IMPORT
######################################################################
import sys
import os
import time
import subprocess
import tempfile
import glob
import platform
import re

######################################################################
# VARIABLES
######################################################################
keilparams = {'build':      '-j0 -b',
              'rebuild':    '-j0 -r',
              'buildall':   '-j0 -z -b',
              'rebuildall': '-j0 -z -r',
              'clean':      '-j0 -c',
              'debug':      '-d',
              'download':   '-j0 -f'}

keil_process = None
tail_process = None

uname = subprocess.getoutput("uname -a")
in_cygwin = re.search(r'cygwin', uname, re.I)
in_wsl    = re.search(r'microsoft', uname, re.I)

flag = 'build'
uvproj = '.'
target = None

for arg in sys.argv[1:]:
    if arg == '-h' or arg == '--help' or arg == 'help':
        print("makekeil [build/rebuild/buildall/rebuildall/clean/debug/download] [*.uvproj] [target]")
        sys.exit()
    elif arg in keilparams:
        flag = arg
    elif os.path.exists(arg):
        uvproj = arg
    else:
        target = arg

uvproj = os.path.abspath(uvproj)
if os.path.isdir(uvproj):
    uvprojs = glob.glob(uvproj + '/*.uvproj')
    if len(uvprojs)==0:
        print("[Error] Not exist uvproj project: " + uvproj)
        sys.exit(-2)
    else:
        uvproj = uvprojs[0]

if target == None:
    print('{}: {}'.format(flag, uvproj))
else:
    print('{}: {} (target="{}")'.format(flag, uvproj, target))
print('Entering directory: {}'.format(os.path.dirname(uvproj)))
sys.stdout.flush()

######################################################################
# FUNCTIONS
######################################################################


######################################################################
# MAIN
######################################################################

if in_wsl:
    # keil not support "\\wsl$\Ubuntu-18.04" path type
    tmpfilename_win = subprocess.getoutput('cmd.exe /c "<nul set /p=%TEMP%\\uv4_%RANDOM%.log" 2>/dev/null')
    tmpfilename = subprocess.getoutput("wslpath -u '{}'".format(tmpfilename_win))
    uvproj_win = subprocess.getoutput("wslpath -w '{}'".format(uvproj))
    open(tmpfilename, 'w').close()
else:
    tmpfilefd, tmpfilename = tempfile.mkstemp()
    os.close(tmpfilefd)
    if in_cygwin:
        uvproj_win = subprocess.getoutput("cygpath -w '{}'".format(uvproj))
        tmpfilename_win = subprocess.getoutput("cygpath -w '{}'".format(tmpfilename))
    else:
        uvproj_win = uvproj
        tmpfilename_win = tmpfilename

keil_cmd = ['UV4.exe'] + keilparams[flag].split() + [uvproj_win, '-o', tmpfilename_win]
if target != None: keil_cmd += ['-t', target]
if in_wsl: tail_cmd = ['powershell.exe', 'Get-Content', tmpfilename_win, '-Wait']
else:      tail_cmd = ['tail', '-f', tmpfilename]
keil_process = subprocess.Popen(keil_cmd)
tail_process = subprocess.Popen(tail_cmd)

while True:
    try:
        keil_process.wait()
        tail_process.kill()
        tail_process.wait()
        time.sleep(0.1)
        break

    except:
        try:
            keil_process.kill()
        except:
            pass

while True:
    if os.path.isfile(tmpfilename):
        try:
            os.unlink(tmpfilename)
        except:
            time.sleep(0.01)
            continue
    break

print('Leaving directory')
sys.stdout.flush()
os.system("reset -w")

# @} #

