#!/usr/bin/bash

#
# New a new bash
#
# Only for cygwin
#

# default window mode is normal
window=''

# check $PATH
if [[ "$PATH" != /bin:* ]]; then
    PATH="/bin:$PATH"
fi

# parse params
for i in "$@"; do
    case "$i" in
        -n) export NOTMUX=1; shift ;;
        -m) window='--window max'; shift ;;
        -s) slash=1; shift ;;
        *)  break ;;
    esac
done

# $TMUX env may lead some strange thing
unset TMUX
unset TMUX_PANE

# Keep PWD
export CHERE_INVOKING=1

# Execute the param
cmds="$@"
if [[ -n "$slash" ]]; then
    cmds="${cmds//\\/\\\\}"
fi
echo "$cmds" > /tmp/.init.tmp

# Start new window
cygstart -w --action=open mintty $window --exec "$SHELL" --login -i
#cmd /C start /I /B "$(cygpath -w -a /bin/mintty)" -

