#!/usr/bin/bash

#
# New a new bash
#
# Only for cygwin
#

# $TMUX env may lead some strange thing
unset TMUX
unset TMUX_PANE

# Keep PWD
export CHERE_INVOKING=1

# Execute the param
echo "$@" > /tmp/.init.tmp

# Start new window
cygstart -w --action=open mintty --exec "$SHELL" --login -i
#cmd /C start /I /B "$(cygpath -w -a /bin/mintty)" -


