#!/usr/bin/bash

#
# New a new bash
#
# Only for cygwin
#

# $TMUX env may lead some strange thing
unset TMUX
unset TMUX_PANE

# new window not startup tmux
export NOTMUX=1

# Keep PWD
echo "cd '$(pwd)'" >> /tmp/.init.tmp

# Execute the param
echo "exec tmuxinator $@" >> /tmp/.init.tmp

# Start new window
cygstart -w --action=open mintty --window max --exec "$SHELL" --login -i
#cmd /C start /I /B "$(cygpath -w -a /bin/mintty)" -


