#!/usr/bin/bash

#
# sudo
#
# Only for cygwin
#

root=$(id -G)
# 544 is windows administrators group
if [[ $root =~ "544" ]]; then
    eval "$@"
    exit
fi

# $TMUX env may lead some strange thing
unset TMUX
unset TMUX_PANE

# Keep PWD
export CHERE_INVOKING=1

# Execute the param
echo "$@" > /tmp/.init.tmp

# Start SUDO window
cygstart -w --action=runas mintty --exec "$SHELL" --login -i

# Kill parent window
kill -9 $PPID

