#!/usr/bin/bash

#
# sudo
#
# Only for cygwin
#

root=$(id -G)
# 544 is windows administrators group
if [[ $root =~ "544" ]]; then
    eval "$@"
    exit
fi

# cygwin-sudo.py is better
if [[ -n "$*" ]]; then
    cygwin-sudo.py "$@"
    exit
fi

# $TMUX env may lead some strange thing
unset TMUX
unset TMUX_PANE

# notmux (use file instead of NOTMUX in tmux)
touch /tmp/.notmux.tmp

# Keep PWD (use file instead of CHERE_INVOKING in tmux)
echo "cd '$(pwd)'" > /tmp/.init.tmp

# Update prompt
echo "prompt_update" >> /tmp/.init.tmp

# Execute the param
echo "$@" >> /tmp/.init.tmp

# Start SUDO window
cygstart -w --action=runas mintty --exec "$SHELL" --login -i

# Check result
if [[ "$?" == "0" ]]; then
    # Kill parent window
    kill -9 $PPID
else
    rm -f /tmp/.notmux.tmp
    rm -f /tmp/.init.tmp
fi


