#!/usr/bin/bash

#
# sudo
#
# Only for cygwin
#

# $TMUX env may lead some strange thing
echo 'unset TMUX' > /tmp/.init.tmp

# Keep PWD
echo "cd '$(pwd)'" >> /tmp/.init.tmp

# Execute the param
echo "$@" >> /tmp/.init.tmp

# Start SUDO window
cygstart -w --action=runas mintty --exec "$SHELL" --login -i

# Kill parent window
kill -9 $PPID

